### ISSUE TITLE
Lien discord expiré :(

### ISSUE THREAD

**Issue by shubs** [ParisDeno/ParisDeno.github.io#1]
Je n'ai pas pu rejoindre la communauté car lien discord expiré :/

**Comment by lsagetlethias** [comment]
Hello ;

Merci pour le retour et désolé de la gène occasionnée 🧐

Je viens de tester le lien en navigation privée et aucun problème de mon côté; 
![image](https://user-images.githubusercontent.com/5783789/82041623-c1e67700-96a8-11ea-994b-4896c9b5bcf7.png)

C'est un lien sans expiration, il ne devrait pas y avoir de soucis pourtant.

En cliquant directement sur ce lien 
https://discord.com/invite/DgFkQQj
vous avez toujours le soucis ?

Pouvez vous copier/coller un sceenshot de l'écran obtenu en cas d'échec ?

**Comment by lsagetlethias** [comment]
@shubs avez vous réussi à accéder à Discord ?

**Comment by lsagetlethias** [comment]
Fermé pour non activité.
